#pragma once

#define MAX_BUFFER_LENGTH 1024
#define DEFAULT_SERVER_PORT 28220
#define DEFAULT_CLIENT_PORT 28210

enum ePacketType
{
	PACKET_TYPE_KICK = 0x0F,
	PACKET_TYPE_REQUEST_JOIN,
	PACKET_TYPE_ALLOW,
	PACKET_TYPE_MESSAGE,

	// IMPORTANT: 마지막을 알기 위함. 패킷 송수신 용도로 쓰지 말 것.
	PACKET_END
};
